port: 7890
socks-port: 7891
mixed-port: 7892
# redir-port: 7892 # é€æ˜ä»£ç†ç«¯å£ï¼Œç”¨äº Linux å’Œ MacOS
# Transparent proxy server port for Linux (TProxy TCP and TProxy UDP)
# tproxy-port: 7893
allow-lan: true
mode: rule
log-level: info
ipv6: true
external-controller: :9090

#è‡ªå®šä¹‰ geodata url
geox-url:
  geoip: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
  geosite: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
  mmdb: "https://fastly.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"

geo-auto-update: false # æ˜¯å¦è‡ªåŠ¨æ›´æ–° geodata
geo-update-interval: 24 # æ›´æ–°é—´éš”ï¼Œå•ä½ï¼šå°æ—¶

dns:
  enabled: true
  prefer-h3: true
  ipv6: true
  default-nameserver:
    - 114.114.114.114
    - 8.8.8.8
      #- system
      #- "udp://223.5.5.5"
  nameserver:
    - https://1.12.12.12/dns-query
    - https://223.6.6.6/dns-query
      #- https://doh.pub/dns-query
      #- https://dns.alidns.com/dns-query

  fallback:
    - https://dns.google/dns-query
    - quic://dns.adguard.com:784
    - https://cloudflare-dns.com/dns-query
  enhanced-mode: fake-ip #redir-host
  fake-ip-range: 198.18.0.1/16
  # å¯è®¾ç½®ä¸ºwhitelistï¼Œå³åªæœ‰åŒ¹é…æˆåŠŸæ‰è¿”å›fake-ip
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - dns.msftncsi.com
    - www.msftncsi.com
    - www.msftconnecttest.com
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - "connect.rom.miui.com"  # å°ç±³è®¾å¤‡æ£€æµ‹
    - "*.msn.com"             # Windowsæ›´æ–°æ£€æµ‹
    - stun.*.*.*
    - stun.*.*
    - miwifi.com
    - rule-set:apple #fakeip-filter #ä¸” behavior å¿…é¡»ä¸º domain/classicalï¼Œå½“ä¸º classical æ—¶ä»…ä¼šç”Ÿæ•ˆåŸŸåç±»è§„åˆ™
    - music.163.com
    - '*.music.163.com'
    - '*.126.net'
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - '*.y.qq.com'
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - '*.xiami.com'
    - '*.music.migu.cn'
    - music.migu.cn
    - netis.cc
    - router.asus.com
    - repeater.asus.com
    - routerlogin.com
    - routerlogin.net
    - tendawifi.com
    - tendawifi.net
    - tplinklogin.net
    - tplinkwifi.net
    - tplinkrepeater.net
    - '*.tpddns.cn'
    - '*.ntp.org.cn'
    - '*.openwrt.pool.ntp.org'
    - localhost.ptlogin2.qq.com
    - '*.*.*.srv.nintendo.net'
    - '*.*.stun.playstation.net'
    - xbox.*.*.microsoft.com
    - '*.ipv6.microsoft.com'
    - '*.*.xboxlive.com'
    - speedtest.cros.wr.pvp.net
  use-hosts: true

  nameserver-policy:
    #"geosite:gfw,geolocation-!cn":
    #  - https://dns.google/dns-query
    #  - quic://dns.adguard.com:784
    #  - https://cloudflare-dns.com/dns-query
    #"geosite:cn,geolocation-cn": ["udp://223.5.5.5", https://doh.pub/dns-query]  # å›½å†…åŸŸåç›´è¿
    #"geosite:category-ads-all": rcode://success
    '+.baidu.com': '114.114.114.114'
    "rule-set:gfw": https://dns.google/dns-query
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
      - 0.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.168.0.0/16
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
    domain:
      - '+.google.com'
      - '+.facebook.com'
      - '+.youtube.com'
      - '+.cloudflare.com'
      - +.twitter.com
      - +.x.com
      - +.xn--ngstr-lra8j.com
      - +.google.cn
      - +.googleapis.cn
      - +.googleapis.com
      - +.gvt1.com
      - +.paoluz.com
      - +.paoluz.link
      - +.paoluz.xyz
      - +.sodacity-funk.xyz
      - +.nloli.xyz
      - +.jsdelivr.net
      - +.proton.me

hosts:
  '*.clash.dev': 127.0.0.1
  'alpha.clash.dev': '::1'
  #test.com: [1.1.1.1, 2.2.2.2]
  #search.com: google.com
  #clash.lan: clash

  #clayton.eu.or: 10.144.84.198
  #jiahe.eu.or: 10.144.100.6
  #'qnap': 10.144.84.198
  #'raspi': 10.144.100.6
  #'hp': 10.144.176.30

sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [ 443 ]
  force-domain:
    - '+.v2ex.com'
  skip-domain:
    - 'Mijia Cloud'
    - 'dlg.io.mi.com'
    - '+.apple.com'
    - '+.local'
cfw-bypass:
  # ç›´è¿åˆ—è¡¨
  # MyList
  - "*.cmbc.com.cn"
  - "*.citicbank.com"
  - "*.cmbchina.com"
  - "*.icbc.com.cn"
  - "*.ccb.com"
  - "*.spdb.com.cn"
  - "*.abchina.com"
  - "*.boc.cn"
  - "*.bankcomm.com"
  - "*.hxb.com.cn"
  - "*.cebbank.com"
  - "*.psbc.com"
  - "*.bankofbeijing.com.cn"
  - "*.95516.com"
  - "*.unionpay.com"
  - qq.com
  - "*.qq.com"
  - music.163.com
  - '*.music.163.com'
  - "www.webofscience.com" # Web of ScienceåŸŸå
  - "snowplow.apps.clarivate.com"
  - "access.clarivate.com"
  - "snowplow-collector.userintel.prod.sp.aws.clarivate.net"
  - "*.13th.tech"
  - "*.423down.com"
  - "*.chaipip.com"
  - "*.chinaplay.store"

  - "*.msftconnecttest.com"
  - "*.msftncsi.com"
  - "*.foxmail.com"
  - localhost
  - 127.*
  - 10.0.0.0/8
  - 172.16.0.0/12
  - 192.168.0.0/16
  - "+.local"
cfw-latency-timeout: 3000

proxy:
  - name: "ProxyH" # é»˜è®¤ä½¿ç”¨çš„å‡ºç«™ä»£ç†åç§°
    type: socks5 # å‡ºç«™ä»£ç†ç±»å‹ï¼Œæ”¯æŒ HTTPã€HTTPSã€SOCKS4 å’Œ SOCKS5ã€‚

proxy-groups:
  - name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
    type: select
    proxies:
      - ğŸ¯ å…¨çƒç›´è¿
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ”° manual
      - Cflare
      - Cfkg
      - Cfop
      - SKR
      - HyunWarp
      - UserC
      - SpecialFilter
  - name: Cfop
    type: url-test
    use:
      - cldop
    url: 'http://www.gstatic.com/generate_204'
    interval: 1200
    icon: https://g.csdnimg.cn/static/logo/favicon32.ico
  - name: SKR
    type: url-test
    use:
      - skr
    url: 'http://www.gstatic.com/generate_204'
    interval: 1200
  - name: Cflare
    type: url-test
    use:
      - cldflare
    url: 'http://www.gstatic.com/generate_204'
    interval: 1200
  - name: Cfkg
    type: url-test
    use:
      - cldkg
    url: 'http://www.gstatic.com/generate_204'
    interval: 1200
  - name: FlyNb
    type: url-test
    use:
      - flynb
    url: 'http://www.gstatic.com/generate_204'
    interval: 12000
  - name: UserC
    type: select
    use:
      - ucust
    url: 'http://www.gstatic.com/generate_204'
    interval: 12000
  - name: XTwitter
    type: select
    proxies:
      - FlyNb
      - UserC
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - SKR
      - HyunWarp
      - ACommon
  - name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 1200
    use:
      - common
  - name: å…¨å±€é€‰æ‹©
    type: select
    proxies:
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - ğŸ›‘ å…¨çƒæ‹¦æˆª
      - ğŸŸ æ¼ç½‘ä¹‹é±¼
      - ğŸ å¤±è´¥åˆ‡æ¢
  - name: ğŸ”° manual
    type: select
    use:
      - common
      - skr
      - hyun-warp
  - name: HyunWarp
    type: url-test
    use:
      - hyun-warp
    url: 'http://www.gstatic.com/generate_204'
    interval: 1200
  - name: "SpecialFilter"
    type: select
    use:
      - hyun-warp
    filter: "Gbps"
    #exclude-type: "vmess|trojan"
      #exclude-filter: ""
  - name: ACommon
    type: url-test
    use:
      - common
    url: 'http://www.gstatic.com/generate_204'
    interval: 1200
  - name: ğŸ¯ å…¨çƒç›´è¿
    type: select
    proxies:
      - DIRECT
  - name: ğŸ›‘ å…¨çƒæ‹¦æˆª
    type: select
    proxies:
      - REJECT
      - DIRECT
  - name: ğŸŸ æ¼ç½‘ä¹‹é±¼
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - name: ğŸ å¤±è´¥åˆ‡æ¢
    type: fallback
    use:
      - cldop
      - cldflare
      - cldkg
      - skr
      - hyun-warp
      - common
    url: 'http://www.gstatic.com/generate_204'
    interval: 1200
  - name: ğŸ“² ç”µæŠ¥ä¿¡æ¯
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
      - SKR
      - HyunWarp

  - name: â“‚ï¸ å¾®è½¯æœåŠ¡
    type: select
    proxies:
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - name: â›”ï¸ å¹¿å‘Šæ‹¦æˆª
    type: select
    proxies:
      - ğŸ›‘ å…¨çƒæ‹¦æˆª
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - name: ğŸš« è¿è¥åŠ«æŒ
    type: select
    proxies:
      - ğŸ›‘ å…¨çƒæ‹¦æˆª
      - ğŸ¯ å…¨çƒç›´è¿
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©

  - name: ğŸ è‹¹æœæœåŠ¡
    type: select
    proxies:
      - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
      - ğŸ¯ å…¨çƒç›´è¿
      - â™»ï¸ è‡ªåŠ¨é€‰æ‹©

proxy-providers:
  common:
    url: "https://jiahe.eu.org:15443/clash_verge/common_proxies.yaml"
    #exclude-type: "Shadowsocks|Http"
    #exclude-filter: "(?i)æ¸¯|hk|hongkong|hong kong"
    #filter: "(?i)æ¸¯|hk|hongkong|hong kong" #(?i) (?A) ç­‰è¯­æ³•æ— æ•ˆ
    type: http
    #type: file
    interval: 3600
    path: local_data/common-proxies.yaml
    health-check:
      enable: true
      interval: 12000
      url: 'http://www.gstatic.com/generate_204'
  hyun-warp:
    type: http
    #type: file
    url: "https://jiahe.eu.org:15443/clash_verge/hyun-proxies.yaml"
    interval: 12411
    path: local_data/hyun-proxies.yaml
    health-check:
      enable: true
      interval: 12000
      url: 'http://www.gstatic.com/generate_204'
  cldflare:
    url: "https://jiahe.eu.org:15443/clash_verge/cloudflare-proxies.yaml"
    type: http
    #type: file
    interval: 10807
    path: local_data/cloudflare-proxies.yaml
    health-check:
      enable: true
      interval: 12000
      url: 'http://www.gstatic.com/generate_204'
  cldkg:
    url: "https://jiahe.eu.org:15443/clash_verge/cfkg-proxies.yaml"
    type: http
    #type: file
    interval: 10807
    path: local_data/cfkg-proxies.yaml
    health-check:
      enable: true
      interval: 12000
      url: 'http://www.gstatic.com/generate_204'
  cldop:
    url: "https://jiahe.eu.org:15443/clash_verge/cf_op_proxies.yaml"
    type: http
    #type: file
    interval: 5612
    path: local_data/cf_op_proxies.yaml
    health-check:
      enable: true
      interval: 960
      url: 'http://www.gstatic.com/generate_204'
  skr:
    url: "https://jiahe.eu.org:15443/clash_verge/skrapp.yaml"
    type: http
    #type: file
    interval: 6622
    path: local_data/skrapp.yaml
    health-check:
      enable: true
      interval: 960
      url: 'http://www.gstatic.com/generate_204'
  flynb:
    url: "https://jiahe.eu.org:15443/clash_verge/flynb-proxies.yaml"
    type: http
    #type: file
    interval: 10807
    path: local_data/flynb-proxies.yaml
    health-check:
      enable: true
      interval: 12000
      url: 'http://www.gstatic.com/generate_204'
  ucust:
    url: "https://jiahe.eu.org:15443/clash_verge/user_custom.yaml"
    type: http
    #type: file
    interval: 933622
    path: local_data/user_custom.yaml
    health-check:
      enable: true
      interval: 186960
      url: 'http://www.gstatic.com/generate_204'

rule-providers:
  reject:
    type: http
    behavior: domain
    #url: from "https://github.com/Loyalsoldier/clash-rules/tree/release"
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

  applications:
    type: http
    behavior: classical
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt"
    path: ./ruleset/applications.yaml
    interval: 86400

  UnBan:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/UnBan.yaml"
    path: ./ruleset/UnBan.yaml
    interval: 86400
  BanAD:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml"
    path: ./ruleset/BanAD.yaml
    interval: 86400
  BanEasyList:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyList.yaml"
    path: ./ruleset/BanEasyList.yaml
    interval: 86400
  BanEasyListChina:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyListChina.yaml"
    path: ./ruleset/BanEasyListChina.yaml
    interval: 86400
  BanEasyPrivacy:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyPrivacy.yaml"
    path: ./ruleset/BanEasyPrivacy.yaml
    interval: 86400
  BanProgramAD:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml"
    path: ./ruleset/BanProgramAD.yaml
    interval: 86400
  GoogleCN:
    type: http
    behavior: classical
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleCN.yaml"
    path: ./ruleset/GoogleCN.yaml
    interval: 86400
  Download:
    type: http
    behavior: classical
    #url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Download.yaml"
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Download.yaml"
    path: ./ruleset/Download.yaml
    interval: 86400
  OneDrive:
    type: http
    behavior: classical
    #url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/OneDrive.yaml"
    url: "https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/OneDrive.yaml"
    path: ./ruleset/OneDrive.yaml
    interval: 86400
  Twitter:
    type: http
    behavior: classical
    #url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/refs/heads/master/Clash/Providers/Ruleset/Twitter.yaml"
    format: 'text' # or 'yaml'
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/clash/classical/twitter.txt"
    path: ./ruleset/Twitter.yaml
    interval: 86400

  cloudflare_ipcidr:
    type: http
    behavior: classical
    format: 'text' # or 'yaml'
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/clash/classical/cloudflare.txt"
      #"https://raw.githubusercontent.com/Loyalsoldier/geoip/refs/heads/release/clash/classical/cloudflare.txt"
      #behavior: ipcidr
      #url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geoip/cloudflare.yaml"
      # https://github.com/Loyalsoldier/geoip/blob/release/clash/ipcidr/cloudflare.txt
    path: ./ruleset/cloudflare_ipcidr.yaml
    interval: 86400

  artificial_direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/FGWong/clash_config/ruleset/manual_direct.yaml"
    path: ./ruleset/manual_direct.yaml
    interval: 86400

  artificial_proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/FGWong/clash_config@main/ruleset/manual_proxy.yaml"
    path: ./ruleset/manual_proxy.yaml
    interval: 86400

  classical_direct:
    behavior: "classical" # domain, ipcidr or classical (ä»…é™ Clash Premium å†…æ ¸)
    type: http # file
    format: 'yaml' # or 'text'
    url: "https://cdn.jsdelivr.net/gh/FGWong/clash_config@main/ruleset/classical_direct.yaml"
    #url: "https://jiahe.eu.org:15443/clash_verge/ruleset/classical_direct.yaml"
    path: ./ruleset/classical_direct.yaml
    interval: 86400

  classical_proxy:
    behavior: "classical" # domain, ipcidr or classical (ä»…é™ Clash Premium å†…æ ¸)
    type: http # file
    format: 'yaml' # or 'text'
    url: "https://cdn.jsdelivr.net/gh/FGWong/clash_config@main/ruleset/classical_proxy.yaml"
    path: ./ruleset/classical_proxy.yaml
    interval: 86400

  passby_proxy:
    behavior: "classical" # domain, ipcidr or classical (ä»…é™ Clash Premium å†…æ ¸)
    type: http # file
    format: 'yaml' # or 'text'
    url: "https://cdn.jsdelivr.net/gh/FGWong/clash_config@main/ruleset/proxy_bypass_cloudflare.yaml"
    path: ./ruleset/proxy_bypass_cloudflare.yaml
    interval: 86400

rules:
  - RULE-SET,classical_direct,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,artificial_direct,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,cloudflare_ipcidr,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,UnBan,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,passby_proxy,XTwitter
  - RULE-SET,classical_proxy,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,artificial_proxy,ğŸš€ èŠ‚ç‚¹é€‰æ‹©

  - RULE-SET,reject,ğŸ›‘ å…¨çƒæ‹¦æˆª
  - RULE-SET,BanAD,ğŸ›‘ å…¨çƒæ‹¦æˆª
  - RULE-SET,BanProgramAD,ğŸ›‘ å…¨çƒæ‹¦æˆª

  - RULE-SET,telegramcidr,ğŸ“² ç”µæŠ¥ä¿¡æ¯
  - RULE-SET,google,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,OneDrive,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,Twitter,XTwitter
  - RULE-SET,apple,ğŸ è‹¹æœæœåŠ¡

  - RULE-SET,proxy,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,lancidr,ğŸ¯ å…¨çƒç›´è¿,no-resolve
  - GEOIP,LAN,ğŸ¯ å…¨çƒç›´è¿,no-resolve

  - RULE-SET,tld-not-cn,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,gfw,ğŸš€ èŠ‚ç‚¹é€‰æ‹©

  - MATCH,ğŸ¯ å…¨çƒç›´è¿
